

services:

  api:
    build: .
    container_name: leveLEO-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: leveleo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis-data: